In [1]:
import pandas as pd
import numpy as np 
from scipy.stats import chi2_contingency

## Assumptions

#### Ho = 'Defective % not varies in 4 centers'
#### Ha = 'Defective % varies in 4 centers'

#### alpha-value = 0.05

In [2]:
df = pd.read_csv('CostomerOrderForm.csv')
df.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [3]:
x = pd.DataFrame([pd.value_counts(df.iloc[:,0]),pd.value_counts(df.iloc[:,1]),pd.value_counts(df.iloc[:,2]),pd.value_counts(df.iloc[:,3])])
x = x.to_numpy()
x

array([[271,  29],
       [267,  33],
       [269,  31],
       [280,  20]], dtype=int64)

In [4]:
table = np.transpose(x)
table

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]], dtype=int64)

#### In this example I am performing Chi Square - Test of Independance with two tail test

In [5]:
test = chi2_contingency(table)
test

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [6]:
p_value = test[1]
p_value

0.2771020991233135

#### As we can see that p-value is greater than the alpha-value. Therefore we 'Fail to Reject Ho'

## Conclusion

#### Defective % not varies in 4 centers